version: '3.7'

services:
  locustapitest:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REPORTFOLDERNAME: locustapitest
    container_name: locustapitest

    ports:
      - 5557:5557